# Configuration file for SpawnerTiers made by Creeperzombi3

Cost:
  default:
    level-2: 7500
    level-3: 12500
    level-4: 20000
    level-5: 40000
  ZOMBIE:
    level-2: 5000
    level-3: 10000
    level-4: 15000
    level-5: 30000
  SKELETON:
    level-2: 6000
    level-3: 12000
    level-4: 20000
    level-5: 35000

Spawners:
